name: CI-test #ワークフロー名
on: push #ワークフローの動作するトリガー
jobs: #jobの定義(実行タスク)
  build:
    runs-on:
    steps: #jobの中で実行されるコマンド
      - name: Push branch #コマンドごとの名前
        run: echo "ブランチをpushしました"
      - name: Checkout
        uses: actions/checkout@v4
        #ランナーにチェックアウト、ビルドなど他のアクションを実行できるようになる
      - name: Setup
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven #キャッシュ
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
